import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Samsung Galaxy A54",
    shortDescription: "5G смартфоны, 8 ГБ жедел жады, 128 ГБ жады",
    fullDescription:
      "Samsung Galaxy A54 5G смартфоны - бұл керемет камера, жоғары өнімділік және ұзақ батарея өмірі бар орта деңгейлі телефон. 6,4 дюймдік Super AMOLED дисплейі бар, 120 Гц жаңарту жиілігі бар.",
    price: 169990,
    image: "https://picsum.photos/id/1/500/500",
    inStock: true,
    specifications: {
      Экран: "6.4 дюйм, Super AMOLED",
      Процессор: "Exynos 1380",
      Жады: "8 ГБ / 128 ГБ",
      Камера: "50 МП + 12 МП + 5 МП",
      Батарея: "5000 мАч",
    },
    category: "Смартфондар",
  },
  {
    id: 2,
    name: "Apple iPhone 15",
    shortDescription: "A16 Bionic чипі, 6 ГБ жедел жады, 128 ГБ жады",
    fullDescription:
      "Apple iPhone 15 - бұл A16 Bionic чипімен жабдықталған жоғары сапалы смартфон. Керемет камера жүйесі, жақсартылған батарея өмірі және Dynamic Island функциясы бар.",
    price: 499990,
    image: "https://picsum.photos/id/2/500/500",
    inStock: true,
    specifications: {
      Экран: "6.1 дюйм, Super Retina XDR",
      Процессор: "A16 Bionic",
      Жады: "6 ГБ / 128 ГБ",
      Камера: "48 МП + 12 МП",
      Батарея: "3877 мАч",
    },
    category: "Смартфондар",
  },
  {
    id: 3,
    name: "Xiaomi Redmi Note 12",
    shortDescription: "Snapdragon 685, 6 ГБ жедел жады, 128 ГБ жады",
    fullDescription:
      "Xiaomi Redmi Note 12 - бұл жақсы бағамен керемет мүмкіндіктер ұсынатын бюджеттік смартфон. AMOLED дисплейі, жақсы камера және жылдам зарядтау мүмкіндігі бар.",
    price: 89990,
    image: "https://picsum.photos/id/3/500/500",
    inStock: true,
    specifications: {
      Экран: "6.67 дюйм, AMOLED",
      Процессор: "Snapdragon 685",
      Жады: "6 ГБ / 128 ГБ",
      Камера: "50 МП + 8 МП + 2 МП",
      Батарея: "5000 мАч",
    },
    category: "Смартфондар",
  },
  {
    id: 4,
    name: "Ноутбук Lenovo IdeaPad 3",
    shortDescription: "Intel Core i5, 8 ГБ жедел жады, 512 ГБ SSD",
    fullDescription:
      "Lenovo IdeaPad 3 - бұл күнделікті тапсырмалар үшін жасалған сенімді ноутбук. Жақсы өнімділік, жеңіл дизайн және ұзақ батарея өмірі бар.",
    price: 249990,
    image: "https://picsum.photos/id/4/500/500",
    inStock: true,
    specifications: {
      Процессор: "Intel Core i5-1135G7",
      Жады: "8 ГБ DDR4",
      Жинақтауыш: "512 ГБ SSD",
      Экран: "15.6 дюйм, Full HD",
      Видеокарта: "Intel Iris Xe Graphics",
    },
    category: "Ноутбуктер",
  },
  {
    id: 5,
    name: "Apple MacBook Air M2",
    shortDescription: "Apple M2 чипі, 8 ГБ жедел жады, 256 ГБ SSD",
    fullDescription:
      "Apple MacBook Air M2 - бұл жаңа M2 чипімен жабдықталған жұқа және жеңіл ноутбук. Керемет өнімділік, ұзақ батарея өмірі және жақсартылған дисплей бар.",
    price: 599990,
    image: "https://picsum.photos/id/5/500/500",
    inStock: false,
    specifications: {
      Процессор: "Apple M2",
      Жады: "8 ГБ",
      Жинақтауыш: "256 ГБ SSD",
      Экран: "13.6 дюйм, Liquid Retina",
      Батарея: "18 сағатқа дейін",
    },
    category: "Ноутбуктер",
  },
  {
    id: 6,
    name: "Asus ROG Strix G15",
    shortDescription: "AMD Ryzen 7, 16 ГБ жедел жады, RTX 3060",
    fullDescription:
      "Asus ROG Strix G15 - бұл ойын ноутбугі, AMD Ryzen 7 процессоры және NVIDIA GeForce RTX 3060 видеокартасымен жабдықталған. Жоғары жаңарту жиілігі бар дисплей және RGB пернетақтасы бар.",
    price: 699990,
    image: "https://picsum.photos/id/6/500/500",
    inStock: true,
    specifications: {
      Процессор: "AMD Ryzen 7 6800H",
      Жады: "16 ГБ DDR5",
      Жинақтауыш: "1 ТБ SSD",
      Экран: "15.6 дюйм, 165 Гц",
      Видеокарта: "NVIDIA GeForce RTX 3060",
    },
    category: "Ноутбуктер",
  },
  {
    id: 7,
    name: "Sony PlayStation 5",
    shortDescription: "8K қолдауы, 825 ГБ SSD, DualSense контроллері",
    fullDescription:
      "Sony PlayStation 5 - бұл келесі буын ойын консолі. Жылдам жүктеу уақыты, керемет графика және инновациялық DualSense контроллері бар.",
    price: 299990,
    image: "https://picsum.photos/id/7/500/500",
    inStock: false,
    specifications: {
      Процессор: "AMD Zen 2",
      Видеокарта: "AMD RDNA 2",
      Жинақтауыш: "825 ГБ SSD",
      Рұқсат: "8K қолдауы",
      Порттар: "HDMI 2.1, USB-A, USB-C",
    },
    category: "Ойын консольдері",
  },
  {
    id: 8,
    name: "Apple Watch Series 9",
    shortDescription: "OLED дисплейі, ЭКГ, SpO2 датчигі",
    fullDescription:
      "Apple Watch Series 9 - бұл денсаулық пен фитнес мүмкіндіктері бар смарт сағат. Әрдайым қосулы дисплей, ЭКГ, оттегі деңгейін өлшеу және көптеген басқа функциялар бар.",
    price: 219990,
    image: "https://picsum.photos/id/8/500/500",
    inStock: true,
    specifications: {
      Дисплей: "OLED, әрдайым қосулы",
      Датчиктер: "ЭКГ, SpO2, жүрек соғу жиілігі",
      "Су өткізбейтін": "50 метрге дейін",
      Байланыс: "Wi-Fi, Bluetooth, GPS",
      Батарея: "18 сағатқа дейін",
    },
    category: "Гаджеттер",
  },
  {
    id: 9,
    name: "Samsung Galaxy Tab S9",
    shortDescription: "11 дюйм AMOLED, S Pen қаламы, 8 ГБ жедел жады",
    fullDescription:
      "Samsung Galaxy Tab S9 - бұл жоғары сапалы Android планшеті. AMOLED дисплейі, S Pen қаламы және жоғары өнімділігі бар. Жұмыс, ойын-сауық және шығармашылық үшін тамаша.",
    price: 399990,
    image: "https://picsum.photos/id/9/500/500",
    inStock: true,
    specifications: {
      Экран: "11 дюйм, AMOLED",
      Процессор: "Snapdragon 8 Gen 2",
      Жады: "8 ГБ / 128 ГБ",
      Батарея: "8400 мАч",
      Қосымша: "S Pen қаламы",
    },
    category: "Планшеттер",
  },
  {
    id: 10,
    name: "JBL Flip 6",
    shortDescription: "Bluetooth колонкасы, су өткізбейтін, 12 сағат ойнату",
    fullDescription:
      "JBL Flip 6 - бұл портативті Bluetooth колонкасы. Жақсы дыбыс сапасы, су өткізбейтін корпус және ұзақ батарея өмірі бар. Сыртта немесе үйде қолдануға өте ыңғайлы.",
    price: 59990,
    image: "https://picsum.photos/id/10/500/500",
    inStock: true,
    specifications: {
      Қуат: "20 Вт",
      Батарея: "12 сағатқа дейін",
      "Су өткізбейтін": "IP67",
      Байланыс: "Bluetooth 5.1",
      Салмағы: "550 г",
    },
    category: "Аудио",
  },
  {
    id: 11,
    name: "Dyson V12 Detect Slim",
    shortDescription: "Сымсыз шаңсорғыш, лазерлік детектор, 60 мин жұмыс",
    fullDescription:
      "Dyson V12 Detect Slim - бұл лазерлік шаң детекторы бар сымсыз шаңсорғыш. Жоғары сору қуаты, ұзақ батарея өмірі және HEPA сүзгісі бар.",
    price: 399990,
    image: "https://picsum.photos/id/11/500/500",
    inStock: true,
    specifications: {
      Қуат: "150 AW",
      Батарея: "60 минутқа дейін",
      Сүзгі: "HEPA",
      "Шаң жинағыш": "0.35 л",
      Салмағы: "2.2 кг",
    },
    category: "Тұрмыстық техника",
  },
  {
    id: 12,
    name: "Philips Airfryer XXL",
    shortDescription: "Ауа фритюрницасы, 2 кг сыйымдылық, 2225 Вт",
    fullDescription:
      "Philips Airfryer XXL - бұл аз майды қолданып тамақ дайындауға арналған ауа фритюрницасы. Үлкен сыйымдылық, жылдам қыздыру және оңай тазалау мүмкіндігі бар.",
    price: 129990,
    image: "https://picsum.photos/id/12/500/500",
    inStock: true,
    specifications: {
      Қуат: "2225 Вт",
      Сыйымдылық: "2 кг",
      Температура: "80-200°C",
      Таймер: "60 минутқа дейін",
      Функциялар: "Қуыру, пісіру, грильдеу",
    },
    category: "Тұрмыстық техника",
  },
  {
    id: 13,
    name: "Nike Air Zoom Pegasus 40",
    shortDescription: "Жүгіру кроссовкалары, ауа жастықшасы, тор материалы",
    fullDescription:
      "Nike Air Zoom Pegasus 40 - бұл күнделікті жүгіруге арналған кроссовкалар. Ыңғайлы, жеңіл және төзімді. Zoom Air жастықшасы бар, бұл жүгіру кезінде жақсы амортизацияны қамтамасыз етеді.",
    price: 64990,
    image: "https://picsum.photos/id/13/500/500",
    inStock: true,
    specifications: {
      Материал: "Тор, синтетика",
      Табан: "Резеңке",
      Технология: "Zoom Air",
      Қолдану: "Жүгіру, күнделікті",
      Салмағы: "255 г",
    },
    category: "Спорт тауарлары",
  },
  {
    id: 14,
    name: "Adidas Ultraboost 23",
    shortDescription: "Жүгіру кроссовкалары, Boost технологиясы, Primeknit",
    fullDescription:
      "Adidas Ultraboost 23 - бұл максималды жайлылық пен өнімділік үшін жасалған премиум жүгіру кроссовкалары. Boost технологиясы энергияны қайтаруды қамтамасыз етеді, ал Primeknit материалы аяққа жақсы отырады.",
    price: 89990,
    image: "https://picsum.photos/id/14/500/500",
    inStock: false,
    specifications: {
      Материал: "Primeknit",
      Табан: "Continental резеңкесі",
      Технология: "Boost",
      Қолдану: "Жүгіру, күнделікті",
      Салмағы: "283 г",
    },
    category: "Спорт тауарлары",
  },
  {
    id: 15,
    name: "Canon EOS R6 Mark II",
    shortDescription: "Айналы фотоаппарат, 24.2 МП, 4K видео",
    fullDescription:
      "Canon EOS R6 Mark II - бұл кәсіби деңгейдегі айналы фотоаппарат. 24.2 МП сенсоры, жылдам автофокус және 4K видео түсіру мүмкіндігі бар. Фотография және видеография үшін тамаша таңдау.",
    price: 1299990,
    image: "https://picsum.photos/id/15/500/500",
    inStock: true,
    specifications: {
      Сенсор: "24.2 МП CMOS",
      Процессор: "DIGIC X",
      Видео: "4K 60fps",
      Автофокус: "1053 нүкте",
      Экран: "3 дюйм, сенсорлы",
    },
    category: "Фото және видео",
  },
  {
    id: 16,
    name: "DJI Mini 3 Pro",
    shortDescription: "Дрон, 4K камера, 34 мин ұшу уақыты",
    fullDescription:
      "DJI Mini 3 Pro - бұл шағын және жеңіл дрон, бірақ кәсіби мүмкіндіктері бар. 4K камера, кедергілерді анықтау жүйесі және ұзақ ұшу уақыты бар. Жол сапарлары мен шығармашылық жобалар үшін тамаша.",
    price: 399990,
    image: "https://picsum.photos/id/16/500/500",
    inStock: true,
    specifications: {
      Камера: "4K 60fps",
      Сенсор: "1/1.3 дюйм CMOS",
      "Ұшу уақыты": "34 минутқа дейін",
      Салмағы: "249 г",
      Қашықтық: "12 км дейін",
    },
    category: "Фото және видео",
  },
  {
    id: 17,
    name: "Bose QuietComfort Ultra",
    shortDescription: "Сымсыз құлаққаптар, шуды басу, 24 сағат ойнату",
    fullDescription:
      "Bose QuietComfort Ultra - бұл премиум сымсыз құлаққаптар. Жоғары деңгейлі шуды басу технологиясы, жақсы дыбыс сапасы және ұзақ батарея өмірі бар. Саяхат, жұмыс немесе күнделікті қолдану үшін тамаша.",
    price: 189990,
    image: "https://picsum.photos/id/17/500/500",
    inStock: true,
    specifications: {
      "Шуды басу": "Адаптивті",
      Батарея: "24 сағатқа дейін",
      Байланыс: "Bluetooth 5.3",
      Микрофон: "4 микрофон жүйесі",
      Қосымша: "Мультипойнт қосылу",
    },
    category: "Аудио",
  },
  {
    id: 18,
    name: "Samsung Odyssey G7",
    shortDescription: "Ойын мониторы, 32 дюйм, 240 Гц, 1 мс",
    fullDescription:
      "Samsung Odyssey G7 - бұл жоғары деңгейлі ойын мониторы. 32 дюймдік қисық экран, 240 Гц жаңарту жиілігі және 1 мс жауап беру уақыты бар. QLED технологиясы керемет түстер мен контрастты қамтамасыз етеді.",
    price: 349990,
    image: "https://picsum.photos/id/18/500/500",
    inStock: true,
    specifications: {
      Экран: "32 дюйм, қисық",
      Рұқсат: "2560x1440 (WQHD)",
      "Жаңарту жиілігі": "240 Гц",
      "Жауап беру уақыты": "1 мс",
      Технология: "QLED",
    },
    category: "Мониторлар",
  },
  {
    id: 19,
    name: "Logitech MX Master 3S",
    shortDescription: "Сымсыз тышқан, 8000 DPI, 7 түйме",
    fullDescription:
      "Logitech MX Master 3S - бұл кәсіби сымсыз тышқан. Жоғары дәлдік, ыңғайлы эргономика және ұзақ батарея өмірі бар. Бірнеше құрылғымен жұмыс істей алады және бағдарламаланатын түймелері бар.",
    price: 59990,
    image: "https://picsum.photos/id/19/500/500",
    inStock: true,
    specifications: {
      Сенсор: "8000 DPI",
      Түймелер: "7 бағдарламаланатын",
      Батарея: "70 күнге дейін",
      Байланыс: "Bluetooth, USB ресивер",
      Қосымша: "MagSpeed айналдыру",
    },
    category: "Компьютер керек-жарақтары",
  },
  {
    id: 20,
    name: "IKEA MARKUS",
    shortDescription: "Офис орындығы, тор арқасы, биіктікті реттеу",
    fullDescription:
      "IKEA MARKUS - бұл ыңғайлы және төзімді офис орындығы. Тор арқасы ауа айналымын қамтамасыз етеді, ал биіктікті реттеу және шалқайту функциялары ұзақ жұмыс күндері үшін жайлылықты қамтамасыз етеді.",
    price: 79990,
    image: "https://picsum.photos/id/20/500/500",
    inStock: true,
    specifications: {
      Материал: "Тор, мата",
      Биіктік: "Реттелетін",
      Шалқайту: "Иә",
      "Максималды салмақ": "110 кг",
      Кепілдік: "10 жыл",
    },
    category: "Жиһаз",
  },
]

export const categories = [
  "Смартфондар",
  "Ноутбуктер",
  "Планшеттер",
  "Аудио",
  "Гаджеттер",
  "Тұрмыстық техника",
  "Спорт тауарлары",
  "Фото және видео",
  "Мониторлар",
  "Компьютер керек-жарақтары",
  "Жиһаз",
  "Ойын консольдері",
]
